### ISSUE TITLE
Adding commands at host

### ISSUE THREAD

**Issue by suniljha555** [nsg-ethz/p4-utils#13]
How can we add commands at host like mentioned in P4 language official tutorials? here

Thank you

**Comment by edgar-costa** [comment]
I added that feature, now you can add `host` commands in the `json` file. However, be careful, those commands have to be nonblocking otherwise the network bootstrap will be blocked. I planned in the past to add a way to schedule commands that could run in the background and be scheduled at some specific times. Hope this helps and i will close the issue.
